"""remove user foreign keys

Revision ID: 4295d3ca814d
Revises: 1ce73defb26a
Create Date: 2026-03-03 19:03:08.765106

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '4295d3ca814d'
down_revision: Union[str, None] = '1ce73defb26a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('conversations_user_id_fkey', 'conversations', type_='foreignkey')
    op.drop_constraint('conversations_trip_id_fkey', 'conversations', type_='foreignkey')
    op.drop_constraint('itineraries_trip_id_fkey', 'itineraries', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('itineraries_trip_id_fkey', 'itineraries', 'trips', ['trip_id'], ['id'])
    op.create_foreign_key('conversations_trip_id_fkey', 'conversations', 'trips', ['trip_id'], ['id'])
    op.create_foreign_key('conversations_user_id_fkey', 'conversations', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###