"""initial tables

Revision ID: 49b12d726d2f
Revises: 4295d3ca814d
Create Date: 2026-03-03 19:05:42.414193

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '49b12d726d2f'
down_revision: Union[str, None] = '4295d3ca814d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('teb_profiles_user_id_fkey', 'teb_profiles', type_='foreignkey')
    op.drop_constraint('trips_user_id_fkey', 'trips', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('trips_user_id_fkey', 'trips', 'users', ['user_id'], ['id'])
    op.create_foreign_key('teb_profiles_user_id_fkey', 'teb_profiles', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###